### ISSUE TITLE
Server crashes when creating more than two clients 

### ISSUE THREAD

**Issue by soniaghongadi** [lisajamhoury/simple-peer-wrapper#1]
Used simple-peer-server and started few instances of simple-peer-wrapper
When sending data, I see the server is crashing with 
ioServer.sockets.sockets[clientIds[i]].join(room);
                                                 ^    

TypeError: Cannot read property 'join' of undefined   
    at SimplePeerServer._handleCreateOrJoin (E:\workspace\hazespear\node_modules\simple-peer-server\src\simple-peer-server.js:105:50)
    at Socket.<anonymous> (E:\workspace\hazespear\node_modules\simple-peer-server\src\simple-peer-server.js:33:14)
    at Socket.emit (events.js:400:28)
    at Socket.emitUntyped (E:\workspace\hazespear\node_modules\socket.io\dist\typed-events.js:69:22)        
    at E:\workspace\hazespear\node_modules\socket.io\dist\socket.js:428:39
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

**Comment by lisajamhoury** [comment]
Thanks for reporting. This is fixed in the most recent version of the simple-peer-server 0.0.8 with commit https://github.com/lisajamhoury/simple-peer-server/commit/8619acdeabe52ed771900bbaada55759769c23ff

The issue was because of a syntax change between socket.io server version 2 and 4. I tested with four clients and appears to be working.
